version: "3"

services:
  app:
    build: .
    command: npm start
    ports: 
      - "1880:1880"
    volumes: 
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    container_name: nodered